before_script:
    - composer self-update
    - composer install
language: php
branches:
  only:
  - master
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
